apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: parallelstore-class
provisioner: parallelstore.csi.storage.gke.io
volumeBindingMode: Immediate
reclaimPolicy: Delete
allowedTopologies:
- matchLabelExpressions:
  - key: topology.gke.io/zone
    values:
    - us-central1-a
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: parallelstore-pv
spec:
  storageClassName: parallelstore-class
  capacity:
    storage: 12000Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  csi:
    driver: parallelstore.csi.storage.gke.io
    volumeHandle: "thomashk-mig/us-central1/parallelstore1/default-pool/default-container"
    volumeAttributes:
      accessPoints: 10.113.134.4,10.113.134.2,10.113.134.3 # These addresses provided after the Parallelstore creation process completed. 
      network: default
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: parallelstore-pvc
spec:
  accessModes:
  - ReadWriteMany
  volumeName: parallelstore-pv
  resources:
    requests:
      storage: 12000Gi # Range from 12,000Gi to 100,000Gi, must be in multiples of 4,000 GiB
  storageClassName: parallelstore-class
